### ISSUE TITLE
It dosen't work on gnome 3.36

### ISSUE THREAD

**Issue by azkia98** [GregTheMadMonk/gnome-cmus-status#1]
Hello XD.

It doesn't work properly  on Manjaro.

gnome 3.36.1.

![Screenshot from 2020-04-27 17-45-33](https://user-images.githubusercontent.com/28800471/80377760-ed97ed80-88b0-11ea-9f61-8c26c49fed94.png)

**Comment by GregTheMadMonk** [comment]
Hi!
Quickly logging back in to Gnome, it seems that I simply forgot to upload the fix to Gnome Extensions (the one from the last commit).
For now, you might use the version from here, but I've noticed that it's kinda broken too (you see the wrong icon on a button lol, also Makefile does not automatically enable it anymore), although is able to do what is is designed to do.
I don't really use Gnome anymore, but I will update the extension here and on Gnome Extensions when I have time (there are some other things I want to add/improve)!

**Comment by azkia98** [comment]
Oh thank you very much.
Now It's working for me.
It's really useful. 
Thanks man XD.


![image](https://user-images.githubusercontent.com/28800471/80542391-22e03080-89c2-11ea-8e7c-4b6fd1f824fd.png)

**Comment by GregTheMadMonk** [comment]
No problem.
Still a lot of stuff to fix though)
btw, is this just a track without tags, or info parsing not working?
