### ISSUE TITLE
Play button does not work on GNOME 3.36

### ISSUE THREAD

**Issue by mbrav** [GregTheMadMonk/gnome-cmus-status#2]
Thanks for the great addon. The side buttons work perfectly, but the play button does not work. 

Running GNOME 3.36 on Pop_OS 20.04

![deepin-screen-recorder_Select area_20200505074639](https://user-images.githubusercontent.com/7410291/81053599-023a3e00-8ece-11ea-8af1-3110885bbb8e.gif)

**Comment by GregTheMadMonk** [comment]
Hello!
Very strange, it works fine for me on both 3.36.2 and 3.36.0 (Arch).
Are you sure you're using the latest extension version (sorry for stupid question)? 
If yes, it seems like it has encountered an error, can you go to the "Looking Glass" and tell me what the error is? (Alt+F2 -> type "lg" -> ENTER -> "Extensions" tab -> locate "cmus status" -> "Show errors")
Thanks for your feedback, and hope we can solve this.

**Comment by mbrav** [comment]
Here is the most I managed to get. 

![Screenshot from 2020-05-06 02-52-20](https://user-images.githubusercontent.com/7410291/81126801-1bca9c80-8f45-11ea-88c0-e558027fb645.png)

**Comment by GregTheMadMonk** [comment]
Thank you!
Should be fixed in the last commits, but will take time to be verified and updated on GNOME Extensions.

**Comment by mbrav** [comment]
Wonderful, I'll test it out once its out and will let you know.

**Comment by mbrav** [comment]
Here is some more info about the error that I found in GNOME's Extension app, hope it helps:

`TypeError: gsettings is null`
`Stack trace:`
  `loadPrefs@/home/user/.local/share/gnome-shell/extensions/cmus-status@yagreg7.gmail.co/prefs.js:240:3`
 `buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/cmus-status@yagreg7.gmail.com/prefs.js:292:8`
 `_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40`
`OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28`
 `asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13`
  `run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20`
  `main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13`
  `run@resource:///org/gnome/gjs/modules/script/package.js:222:19`
  `start@resource:///org/gnome/gjs/modules/script/package.js:206:5`
  `@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17`

**Comment by GregTheMadMonk** [comment]
It has been verified and is available now on GNOME extensions.
If the problem persists, please report it.
If there's no response, I will be closing the issue in around 24 hours
