### ISSUE TITLE
GNOME 40+ compatibility

### ISSUE THREAD

**Issue by icolquhoun** [GregTheMadMonk/gnome-cmus-status#4]
I use this extension all of the time. Any chance of seeing an update to GNOME 40+?

**Comment by GregTheMadMonk** [comment]
I was thinking about updating it for GNOME 40, but there were no requests (and I don't personally use GNOME or cmus anymore). But since there is now, I'll look more into it in my spare time :) I'll write here if there's any progress.

**Comment by GregTheMadMonk** [comment]
Ok @icolquhoun I've pushed a commit to make it work on GNOME 40. Works for me, at least. You could test it and tell if something is wrong if you want. If you don't, I'll be also updating it on AUR and "GNOME Extensions" website, but, if you install extensions from the latter, know that verification process there usually takes some time. If everything works for you, feel free to close the issue.

**Comment by GregTheMadMonk** [comment]
Ok so the extension has been verified on GNOME Extensions, so I'd be closing this issue. Feel free to re-open if problems arise.
